### ISSUE TITLE
ResNet_RS pre-trained 

### ISSUE THREAD

**Issue by api5454** [AmberzzZZ/backbones#1]
Hello, and thank you for this excellent work,
But I was wondering about the possibility of obtaining weights
```resnet50_weights_tf_dim_ordering_tf_kernels.h5```

If there is no way to get it, can you give some advice about training it on data ImageNet,
For your information, I have downloaded resnet50 standard weights  from [TF-V1 and TF-v2](https://github.com/fchollet/deep-learning-models/releases/download/v0.1/resnet50_weights_tf_dim_ordering_tf_kernels.h5) and the number of layers mismatch appears,
Or this error<..
```ValueError: You are trying to load a weight file containing 107 layers into a model with 139 layers.```

and,
Can I take advantage of the following checkpoints?? ,

## ImageNet Checkpoints from [TF.tpu.official](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs)

We release configs and checkpoints of the ResNet-RS model family trained on ImageNet in Tensorflow 1.

| Model        | Input Size    | V100 Lat (s) | TPU Lat (ms)    |   Top-1 Accuracy  |   Download |
| ------------ |:-------------:| -----------:|--------:|-----------:|-----------:|
| ResNet-RS-50 | 160x160  | 0.31 | 70  | 78.8 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs50_i160.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-50-i160.tar.gz) |
| ResNet-RS-101 | 160x160 | 0.48 | 120 | 80.3 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs101_i160.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-101-i160.tar.gz) |
| ResNet-RS-101 | 192x192 | 0.70 | 170 | 81.2 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs101_i192.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-101-i192.tar.gz) |
| ResNet-RS-152 | 192x192 | 0.99 | 240 | 82.0 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs152_i192.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-152-i192.tar.gz) |
| ResNet-RS-152 | 224x224 | 1.48 | 320 | 82.2 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs152_i224.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-152-i224.tar.gz) |
| ResNet-RS-152 | 256x256 | 1.76 | 410 | 83.0 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs152_i256.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-152-i256.tar.gz) |
| ResNet-RS-200 | 256x256 | 2.86 | 570 | 83.4 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs200_i256.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-200-i256.tar.gz) |
| ResNet-RS-270 | 256x256 | 3.76 | 780 | 83.8 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs270_i256.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-270-i256.tar.gz) |
| ResNet-RS-350 | 256x256 | 4.72 | 1100| 84.0 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs350_i256.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-350-i256.tar.gz) |
| ResNet-RS-350 | 320x320 | 8.48 | 1630| 84.2 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs350_i320.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-350-i320.tar.gz) |
| ResNet-RS-420 | 320x320 | 10.16 | 2090| 84.4 | [config](https://github.com/tensorflow/tpu/tree/master/models/official/resnet/resnet_rs/configs/resnetrs420_i320.yaml) \| [ckpt](https://storage.googleapis.com/cloud-tpu-checkpoints/resnet-rs/resnet-rs-420-i320.tar.gz) |

Thank you and good luck to you anyway

**Comment by AmberzzZZ** [comment]
as you can see there's a little modification on the network architecture from resnet to resnet_rs(the stem & the se_block).
so it's not possible to load the h5 file directly to this model.
but you can try to load the weights layer by layer(as the work i did in covert* scripts).
currently there's some tf version problem so i'm not able to parse the official ckpts correctly but i'm still working on.
after the work is done the convert script would be pushed :)

**Comment by api5454** [comment]
Thanks for your advice
I got you
Until this time we will close this..
